# Generated by Django 3.2.16 on 2022-10-14 17:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите марку автомобиля', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите модель автомобиля', max_length=200)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesmanager.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите цвет автомобиля', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID заказа автомобиля', primary_key=True, serialize=False)),
                ('ammount', models.IntegerField(help_text='Введите колличество автомобилей')),
                ('order_date', models.DateField(blank=True)),
                ('color_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesmanager.color')),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesmanager.carmodel')),
            ],
            options={
                'ordering': ['order_date'],
            },
        ),
    ]
