# Generated by Django 3.2.16 on 2022-10-14 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanager', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 14, 21, 27, 9, 648612)),
        ),
    ]
