# Generated by Django 3.2.16 on 2022-10-14 18:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanager', '0005_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 14, 18, 34, 6, 588193, tzinfo=utc)),
        ),
    ]
