# Generated by Django 3.2.16 on 2022-10-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanager', '0007_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['brand_name']},
        ),
    ]
