# Generated by Django 3.2.16 on 2022-10-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmanager', '0010_rename_ammount_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(help_text='Введите марку автомобиля', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(help_text='Введите цвет автомобиля', max_length=200, unique=True),
        ),
    ]
